import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  if (status === "loading") {
    return <main>Loading...</main>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
          Guestbook
        </h1>
        {session ? (
          <>
            <p>Welcome, {session.user?.name}</p>
            <button onClick={() => signOut()}>Log Out</button>
          </>
        ) : (
          <button onClick={() => signIn("discord")}>Login with Discord</button>
        )}
      </main>
    </>
  );
};

export default Home;
